name = "examples"
version = "1.0.0"

# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }

target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
teashop = { path = "../teashop" }
loose_leaf = { path = ".." }

[dev-dependencies]
gleeunit = "~> 1.0"
